from pathlib import Path
import importlib
import json
import sys

import pandas as pd
import numpy as np
import ast
from sklearn.preprocessing import StandardScaler, MultiLabelBinarizer


DATASET_DIR = Path(__file__).resolve().parent / "ptb-xl-a-large-publicly-available-electrocardiography-dataset-1.0.3"

TABULAR_NUMERIC_COLS = ['age', 'height', 'weight']
TABULAR_CATEGORICAL_COLS = ['sex', 'site', 'device', 'nurse', 'heart_axis', 'infarction_stadium1', 'infarction_stadium2']
TABULAR_BINARY_COLS = [
    'second_opinion',
    'initial_autogenerated_report',
    'validated_by_human',
    'baseline_drift',
    'static_noise',
    'burst_noise',
    'electrodes_problems',
    'extra_beats',
    'pacemaker',
]


def _normalize_category(value):
    if pd.isna(value):
        return 'missing'
    value = str(value).strip()
    return value if value and value.lower() != 'nan' else 'missing'


def _normalize_binary(value):
    if pd.isna(value):
        return 0
    value = str(value).strip().lower()
    if not value or value == 'nan':
        return 0
    return 1

def load_raw_data(df, sampling_rate, path):
    """Loads waveform data from .dat/.hea files."""
    wfdb = importlib.import_module("wfdb")
    base_path = Path(path)
    filenames = df.filename_lr if sampling_rate == 100 else df.filename_hr
    total = len(filenames)
    signals = []

    for i, f in enumerate(filenames, start=1):
        signal, _ = wfdb.rdsamp(str(base_path / f))
        signals.append(signal)

        if i == 1 or i == total or i % max(1, total // 100) == 0:
            percent = (i / total) * 100
            sys.stdout.write(f"\rLoading ECG waveforms: {i}/{total} ({percent:.1f}%)")
            sys.stdout.flush()

    print()
    return np.array(signals)

def preprocess_dataset(path=DATASET_DIR, output_dir=None):
    # 1. Load tabular metadata and parse codes
    print("Loading metadata...")
    path = Path(path)
    if output_dir is None:
        output_dir = path.parent / "processed"
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    Y = pd.read_csv(path / 'ptbxl_database.csv', index_col='ecg_id')
    Y.scp_codes = Y.scp_codes.apply(lambda x: ast.literal_eval(x))

    # 2. Extract and Preprocess Tabular Features (X_tab)
    print("Processing tabular metadata...")
    tabular_parts = []

    # Numeric fields
    numeric_df = Y[TABULAR_NUMERIC_COLS].copy()
    for col in TABULAR_NUMERIC_COLS:
        numeric_df[col] = pd.to_numeric(numeric_df[col], errors='coerce')
        numeric_df[col] = numeric_df[col].fillna(numeric_df[col].median())
    scaler = StandardScaler()
    numeric_scaled = pd.DataFrame(
        scaler.fit_transform(numeric_df),
        index=Y.index,
        columns=TABULAR_NUMERIC_COLS,
    )
    tabular_parts.append(numeric_scaled)

    # Categorical fields
    categorical_df = Y[TABULAR_CATEGORICAL_COLS].copy().applymap(_normalize_category)
    categorical_encoded = pd.get_dummies(categorical_df, columns=TABULAR_CATEGORICAL_COLS, prefix_sep='__')
    tabular_parts.append(categorical_encoded)

    # Binary quality / metadata flags
    binary_df = Y[TABULAR_BINARY_COLS].copy().applymap(_normalize_binary)
    tabular_parts.append(binary_df)

    # Combine all tabular features
    X_tab = pd.concat(tabular_parts, axis=1)

    # 3. Load and Aggregate Target Labels (Y)
    print("Aggregating diagnostic targets...")
    agg_df = pd.read_csv(path / 'scp_statements.csv', index_col=0)
    agg_df = agg_df[agg_df.diagnostic == 1]

    def aggregate_diagnostic(y_dic):
        tmp = []
        for key in y_dic.keys():
            if key in agg_df.index:
                tmp.append(agg_df.loc[key].diagnostic_class)
        return list(set(tmp))

    Y['diagnostic_superclass'] = Y.scp_codes.apply(aggregate_diagnostic)
    
    # Binarize multi-label targets for Binary Cross Entropy
    mlb = MultiLabelBinarizer()
    Y_bin = mlb.fit_transform(Y['diagnostic_superclass'])
    Y_labels = pd.DataFrame(Y_bin, index=Y.index, columns=mlb.classes_)

    # 3b. Encode the raw SCP multi-label codes as an explicit third modality
    print("Encoding raw SCP codes as a third modality...")
    scp_mlb = MultiLabelBinarizer()
    scp_code_lists = Y.scp_codes.apply(lambda d: [k for k in d.keys()])
    X_scp = scp_mlb.fit_transform(scp_code_lists)
    X_scp = pd.DataFrame(X_scp, index=Y.index, columns=scp_mlb.classes_)

    # 4. Load Raw ECG Signal Data (X_ecg)
    print("Loading 500Hz ECG waveforms... (This may take a moment)")
    X_ecg = load_raw_data(Y, sampling_rate=500, path=path)

    # 5. Split data into Train and Test based on strat_fold
    test_fold = 10
    train_mask = Y.strat_fold != test_fold
    test_mask = Y.strat_fold == test_fold

    # Train splits
    X_ecg_train = X_ecg[train_mask]
    X_tab_train = X_tab[train_mask].to_numpy(dtype=np.float32)
    X_scp_train = X_scp[train_mask].to_numpy(dtype=np.float32)
    y_train = Y_labels[train_mask].to_numpy(dtype=np.float32)

    # Test splits
    X_ecg_test = X_ecg[test_mask]
    X_tab_test = X_tab[test_mask].to_numpy(dtype=np.float32)
    X_scp_test = X_scp[test_mask].to_numpy(dtype=np.float32)
    y_test = Y_labels[test_mask].to_numpy(dtype=np.float32)

    print("Data shapes:")
    print(f"X_ecg_train: {X_ecg_train.shape}")
    print(f"X_tab_train: {X_tab_train.shape}")
    print(f"X_scp_train: {X_scp_train.shape}")
    print(f"y_train: {y_train.shape}")

    # Save processed arrays for later training steps
    np.save(output_dir / 'X_ecg_train.npy', X_ecg_train)
    np.save(output_dir / 'X_tab_train.npy', X_tab_train)
    np.save(output_dir / 'X_scp_train.npy', X_scp_train)
    np.save(output_dir / 'y_train.npy', y_train)
    np.save(output_dir / 'X_ecg_test.npy', X_ecg_test)
    np.save(output_dir / 'X_tab_test.npy', X_tab_test)
    np.save(output_dir / 'X_scp_test.npy', X_scp_test)
    np.save(output_dir / 'y_test.npy', y_test)

    with open(output_dir / 'preprocessing_info.json', 'w', encoding='utf-8') as f:
        json.dump(
            {
                'dataset_dir': str(path),
                'tabular_numeric_cols': TABULAR_NUMERIC_COLS,
                'tabular_categorical_cols': TABULAR_CATEGORICAL_COLS,
                'tabular_binary_cols': TABULAR_BINARY_COLS,
                'diagnostic_classes': list(mlb.classes_),
                'scp_modalities': list(scp_mlb.classes_),
                'output_files': {
                    'X_ecg_train': 'X_ecg_train.npy',
                    'X_tab_train': 'X_tab_train.npy',
                    'X_scp_train': 'X_scp_train.npy',
                    'y_train': 'y_train.npy',
                    'X_ecg_test': 'X_ecg_test.npy',
                    'X_tab_test': 'X_tab_test.npy',
                    'X_scp_test': 'X_scp_test.npy',
                    'y_test': 'y_test.npy',
                },
            },
            f,
            indent=2,
        )
    print(f"Saved preprocessed data to: {output_dir}")
    
    return X_ecg_train, X_tab_train, X_scp_train, y_train, X_ecg_test, X_tab_test, X_scp_test, y_test

# Usage:
# X_ecg_train, X_tab_train, X_scp_train, y_train, X_ecg_test, X_tab_test, X_scp_test, y_test = preprocess_dataset(DATASET_DIR)


if __name__ == "__main__":
    preprocess_dataset(DATASET_DIR)